---
name: Golangci-lint

on:
  push:
    branches:
      - "main"
    paths:
      - "**.go"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  golangci:
    strategy:
      matrix:
        go: ["1.17", "1.18", "1.19"]
        os: [ubuntu-latest, windows-latest]
    name: Run golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Golang lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: ./...
          only-new-issues: true
